### PR TITLE
Fixed SiteBranding CSS bug for generated sites

### LINKED ISSUE #219: Site branding not applied in SiteGenerator from repository
When using the Serve option the workspace is built from the DSL before the site branding css file is generated, however when doing a Generate the workspace model is not built till after that stage resulting in the default site-branding css.

I'm going to work on resolving this but just wanted to report it first. I'm thinking that one possible way to resolve this would be to move the site-branding css file to the branch directory which would allow different branches to have different color schemes.

### PR DESCRIPTION
**Pull request by qtzar**
When using the 'generate' command the generation of the site-branding.css file was occurring before the workspace DSL had been read in to memory meaning that it was always using the defaults instead of any properties in the DSL.

I've moved the call to 'copySiteWideAssets' to after the DSL is read in for both the local workspace DSL and for repository based DSLs. In the case of a repository based DSL the copySiteWideAssets call is only done once on the default branch.

Fixes #219

### CODE REVIEW

**Comment by jp7677** [comment]
The [copySiteWideAssets](https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt#L14) method only copies static content. Moving this call further down really shouldn’t make a difference.

The generating of the branding stylesheet happens later in https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt#L65

**Review by jp7677 — CHANGES_REQUESTED** [review]
See comment above.

**Comment by qtzar** [comment]
oh I think you are right and I did a bad test on my side.

I'm seeing the issue because I build three branches and the last branch that I build does not have any custom style on the dsl so I get the defaults and that is overwriting the site-branding.css file in the root and being applied to all sites.

I'm going to redo this PR and rewrite it to move the site-branding.css to the branch directory and have it loaded from there depending on which branch is being viewed.

File: src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt [hunk 1]
```diff
@@ -74,11 +74,12 @@ private fun copyAssets(assetsDir: File, exportDir: File) {
 }
 
 private fun generateStyle(context: GeneratorContext, exportDir: File) {
+    val branchDir = File(exportDir, context.currentBranch)
```
Comment (jp7677) [inline src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt:77]: Let’s move this to line 63 as

```kotlin
val branchDir = File(exportDir, currentBranch)
```

then we can just pass branchDir directly into `deleteOldHashes`, `copyAssets`, `generateStyle` and `generateHtmlFiles`.

`deleteHashes` has the same issue that it is applied for all branches, but since the hashes are only used for hot reloading with serve and a single branch, it never surfaced.

Comment (jp7677) [reply src/main/kotlin/nl/avisi/structurizr/site/generatr/site/SiteGenerator.kt:77]: I wonder if we even need `GeneratorContext.currentBranch` after this change. May be it is unused now and can be removed.

**Review by jp7677 — CHANGES_REQUESTED** [review]
See comments.

Do you dare to drop the first two commits with git interactive rebase and git push force? This would keep the commits less cluttered for this PR.

**Comment by qtzar** [comment]
@jp7677 I've made the changed on the comments you left but I've noticed something unusual in addition to the fix above.

When you generate a site ( or local serve ) there is a 'puml' and 'svg' directory created in the root folder with names of the files duplicated in the filename, for example if you have a softwareSystem called `MySystem` there is a file created called `MySystem-SystemContext-MySystem-SystemContext.puml` while in the branch folders puml folder there is a similar file called `MySystem-SystemContext.puml`

I'm wondering if this is a bug of some sort. It seems to happen during the `generateHtmlFiles` stage of the process.

**Comment by jp7677** [comment]
> @jp7677 I've made the changed on the comments you left but I've noticed something unusual in addition to the fix above.

Thanks a lot, looks good and cool that you were able to drop the first two commits.

> When you generate a site ( or local serve ) there is a 'puml' and 'svg' directory created in the root folder with names of the files duplicated in the filename, for example if you have a softwareSystem called `MySystem` there is a file created called `MySystem-SystemContext-MySystem-SystemContext.puml` while in the branch folders puml folder there is a similar file called `MySystem-SystemContext.puml`
> 
> I'm wondering if this is a bug of some sort. It seems to happen during the `generateHtmlFiles` stage of the process.

This is the working directory for creating the embedded/clickable diagrams (https://github.com/avisi-cloud/structurizr-site-generatr/blob/main/src/main/kotlin/nl/avisi/structurizr/site/generatr/site/DiagramGenerator.kt#L37). Here we always pass the root exportDir as location. As far as I’m seeing this is fine, since we also check the definition of the diagrams when deciding if they are up to date or not. As a side effect this greatly improves performance by not repeatedly generating the same diagrams across multiple branches.

**Review by jp7677 — APPROVED** [review]

**Comment by jp7677** [comment]
LGTM, I’ll do a brief test when being again in front of my machine (unless @dirkgroot beats me), though I expect this PR to be fine and will merge afterwards.
